const postsData = [
  {
    id: 1,
    name: "NicolasRuiz",
    followStatus: "Unfollow",
    date: "1 day ago",
    readTime: "2 min",
    profilePicture: require("../assets/Images/nicolas.png"),
    Image: require("../assets/Images/pasta.jpg"),
    Title: "Delicious Homemade Pasta",
    Category: "Cooking",
    Text: "Just made my own homemade pasta from scratch for the first time! Used a traditional recipe with flour and eggs. The result was amazing. Can't believe I made it myself!",
  },
  {
    id: 2,
    name: "DishaMurke",
    followStatus: "Unfollow",
    date: "1 day ago",
    readTime: "3 min",
    profilePicture: require("../assets/Images/disha.png"),
    image: require("../assets/Images/run.jpg"),
    Title: "Personal Best in 5K Run!",
    Category: "Sports",
    Text: "Set a new personal record in my 5K run today! Finished in 22 minutes, breaking my previous record by 1 minute. Hard work and consistent training pay off!",
  },
  {
    id: 3,
    name: "HemanthKumar",
    followStatus: "Unfollow",
    date: "2 days ago",
    readTime: "4 min",
    profilePicture: require("../assets/Images/hemanth.png"),
    image: require("../assets/Images/drawing.jpg"),
    Title: "Captured a Scenic Landscape",
    Category: "Drawing",
    Text: "Spent the afternoon drawing a beautiful landscape. Added vibrant colors and focused on capturing the details. So proud of how it turned out!",
  },
  {
    id: 4,
    name: "SoulHudson",
    followStatus: "Unfollow",
    date: "1 day ago",
    readTime: "1 min",
    profilePicture: require("../assets/Images/josue.png"),
    image: require("../assets/Images/software.png"),
    Title: "Launched My First Mobile App",
    Category: "Software",
    Text: "After months of coding and testing, I finally launched my first mobile app! It's a productivity tool to help users stay organized. Excited to see it in action!",
  },
];

export default postsData;
